//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAlumnos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno_grado
    {
        public int Id { get; set; }
        public int AlumnoId { get; set; }
        public int GradoId { get; set; }
        public int SeccionId { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual grado grado { get; set; }
        public virtual seccion seccion { get; set; }
    }
}
