//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAlumnos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class grado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public grado()
        {
            this.alumno_grado = new HashSet<alumno_grado>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int ProfesorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumno_grado> alumno_grado { get; set; }
        public virtual profesor profesor { get; set; }
    }
}
